In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
import roboticstoolbox as rtb
from spatialmath import *
from spatialmath.base import *

In [3]:
%matplotlib qt
im = cv2.imread('photo.jpg')
plt.imshow(im[:,:,::-1])
plt.show

<function matplotlib.pyplot.show(*, block=None)>

In [9]:
A = np.load('depth.npy')

In [14]:
A.max()

254.99998

In [2]:
# A = np.array([[507.441511, 0, 307.533215],[0, 509.477448, 270.604765],[0, 0, 1]])
# A = np.array([[525, 0, 319.5],[0, 525, 239.5],[0, 0, 1]]) # Default calib
A = np.array([[554.2547, 0, 320.5],[0, 554.2547, 240.5],[0, 0, 1]]) # Gazebo calib
m = np.array([431, 270, 1])
print()

In [28]:
T = np.concatenate((np.eye(3),np.zeros((3,1))),axis=1)
M = np.array([1,2,3,1]).T
print(T.dot(M))

[1. 2. 3.]


In [39]:
x = (m[0]-A[0,2])/A[0,0]
y = (m[1]-A[1,2])/A[1,1]
print(x,y)

0.19691111027975494 -0.010276003816211987


In [39]:
x1 = 319
x2 = 319+36
print((x1-A[0,2])/A[0,0])
print((x2-A[0,2])/A[0,0])
print(((x2-A[0,2])/A[0,0]-(x1-A[0,2])/A[0,0])*(1/1))

-0.0027063369963303877
0.06224575091559892
0.0649520879119293


In [65]:
y1 = 0
y2 = 5
print((y1-A[1,2])/A[1,1])
print((y2-A[1,2])/A[1,1])
print(((y2-A[1,2])/A[1,1]-(y1-A[1,2])/A[1,1])*(1/1))

-0.4339160317449722
-0.42489490842387084
0.009021123321101332


In [3]:
np.set_printoptions(suppress=True)
Tcam = transl(0.49,0.25,0).dot(trotz(np.pi/2)).dot(trotx(np.pi))
Tcam

array([[ 0.  ,  1.  ,  0.  ,  0.49],
       [ 1.  , -0.  , -0.  ,  0.25],
       [ 0.  ,  0.  , -1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [4]:
pix_x = 312
pix_y = 278
x_cam = (pix_x-A[0,2])/A[0,0]
y_cam = (pix_y-A[1,2])/A[1,1]
Pcam = np.array([x_cam, y_cam, 1, 1])
Pcam

array([-0.01533591,  0.06765842,  1.        ,  1.        ])

In [6]:
Pori = Tcam.dot(Pcam)
Pori

array([ 0.55765842,  0.23466409, -1.        ,  1.        ])